In [1]:
import pandas as pd
import numpy as np
from sklearn import cross_validation
from sklearn import linear_model
from sklearn import preprocessing

D:\annoconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
train_df = pd.read_csv('data/train.csv')
test_df = pd.read_csv('data/test.csv')

In [53]:
raw_train_df = train_df.copy()
raw_test_df = test_df.copy()

In [54]:
print(len(test_df.columns))
print(len(train_df.columns))
print('需要处理的非空给的column的个数是'+str((train_df.isnull().sum().values!=0).sum())) 
#这样可以看看 是不是所有的空的行都被处理了 pd.isnull后是DataFrame sum后是Series
pd.set_option('display.max_rows', 50)  #设置显示的最大行数
train_df.info()

80
81
需要处理的非空给的column的个数是19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object

In [55]:
test_df.isnull().sum()

Id                  0
MSSubClass          0
MSZoning            4
LotFrontage       227
LotArea             0
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
                 ... 
Functional          2
Fireplaces          0
FireplaceQu       730
GarageType         76
GarageYrBlt        78
GarageFinish       78
GarageCars          1
GarageArea          1
GarageQual         78
GarageCond         78
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1456
Fence            1169
MiscFeatur

In [56]:
discard_columns = ['Alley', 'PoolQC', 'MiscFeature', 'Fence', 'FireplaceQu']
train_mean_value_list = ['LotFrontage', 'MasVnrArea','GarageYrBlt']
train_object_list = ['MasVnrType', 'BsmtQual', 'BsmtCond', 'Electrical', 'BsmtExposure', 'BsmtFinType1','BsmtFinType2','GarageType','GarageFinish','GarageQual','GarageCond']

In [57]:
#######后加的  一开始是以train集中为空的column为准，发现漏了好多，好多train不空，test中为空，出现问题#############
#上面是直接眼看的，这次改进了！！！
test_null_list = test_df.isnull().sum().index[(test_df.isnull().sum().values)!=0].tolist()
print(len(test_null_list))
test_null_list

33


['MSZoning',
 'LotFrontage',
 'Alley',
 'Utilities',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'BsmtFullBath',
 'BsmtHalfBath',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'SaleType']

In [58]:
a = np.array([1,2,3]) #list不支持bool值读取
print(a)
print(set(a))
a[[True, False, True]]

[1 2 3]
{1, 2, 3}


array([1, 3])

In [59]:
#把需要处理的合并成一个列表，包括train和test
temp_list = []
for i in test_null_list:
    print(test_df[i].dtype)
    temp_list.append(test_df[i].dtype)
print(np.array(temp_list) == 'object')
test_object_list = list(set(np.array(test_null_list)[np.array(temp_list) == 'object'])-set(discard_columns))
len(test_object_list)

object
float64
object
object
object
object
object
float64
object
object
object
object
float64
object
float64
float64
float64
float64
float64
object
object
object
object
float64
object
float64
float64
object
object
object
object
object
object
[ True False  True  True  True  True  True False  True  True  True  True
 False  True False False False False False  True  True  True  True False
  True False False  True  True  True  True  True  True]


17

In [60]:
test_mean_list = list(set(test_null_list)-set(test_object_list)-set(discard_columns))
print(test_object_list)
len(test_mean_list)

['Functional', 'Exterior2nd', 'SaleType', 'BsmtCond', 'BsmtExposure', 'BsmtQual', 'Utilities', 'BsmtFinType1', 'MasVnrType', 'GarageFinish', 'MSZoning', 'BsmtFinType2', 'GarageCond', 'Exterior1st', 'GarageType', 'GarageQual', 'KitchenQual']


11

In [61]:
for i in test_object_list:
    if i not in train_object_list:
        train_object_list.append(i)
for i in test_mean_list:
    if i not in train_mean_value_list:
        train_mean_value_list.append(i)
print(len(train_object_list))
print(len(train_mean_value_list))
train_object_list

18
11


['MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'Electrical',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'Functional',
 'Exterior2nd',
 'SaleType',
 'Utilities',
 'MSZoning',
 'Exterior1st',
 'KitchenQual']

In [62]:
train_test = [train_df, test_df]#放到一个列表中用循环一起处理
for df in train_test: 
    df.drop(discard_columns, axis=1, inplace = True)
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
Id               1460 non-null int64
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non

In [63]:
for column in train_mean_value_list:
    for df in train_test:
        df[column].fillna(value=df[column].mean(), inplace=True)

for column in train_object_list:
    for df in train_test:
        df[column].fillna(df[column].mode()[0], inplace=True)
print(test_df.isnull().sum())
train_df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
                ..
BedroomAbvGr     0
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 75, dtype: int64


Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
Street           0
LotShape         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Condition2       0
BldgType         0
HouseStyle       0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
RoofStyle        0
RoofMatl         0
Exterior1st      0
Exterior2nd      0
MasVnrType       0
                ..
KitchenAbvGr     0
KitchenQual      0
TotRmsAbvGrd     0
Functional       0
Fireplaces       0
GarageType       0
GarageYrBlt      0
GarageFinish     0
GarageCars       0
GarageArea       0
GarageQual       0
GarageCond       0
PavedDrive       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 76, dtype: int64

In [64]:
a = np.array([[1,2,3]])
b = a.copy()
c = b.copy()
c[0] = 0
print(b.all())
(a==b).all(keepdims=True)
a = np.array([[True, True]])
b = np.array([[True, False]])
np.logical_or(a, b)

True


array([[ True,  True]], dtype=bool)

In [65]:
##################对数值型的做transform##########


print(train_df['Street'].mode())#mode 是众数
print(train_df.dtypes)
a = np.array([[1]])

print(np.logical_or((train_df.dtypes.values=='float64'),(train_df.dtypes.values=='int64')))
number_column_index = np.logical_or((train_df.dtypes.values=='float64'),(train_df.dtypes.values=='int64'))
number_columns = train_df.columns[number_column_index].tolist()

str_columns_index = train_df.dtypes.values=='object' #bool类型 为了下面取索引的
str_columns = train_df.columns[str_columns_index].tolist()


print(str_columns_index)
print(len(number_columns))
print(len(train_df.columns))
len(str_columns)
print(str_columns)
print(number_columns)
# print(train_df.columns)
number_columns[0:2]

0    Pave
dtype: object
Id                 int64
MSSubClass         int64
MSZoning          object
LotFrontage      float64
LotArea            int64
Street            object
LotShape          object
LandContour       object
Utilities         object
LotConfig         object
LandSlope         object
Neighborhood      object
Condition1        object
Condition2        object
BldgType          object
HouseStyle        object
OverallQual        int64
OverallCond        int64
YearBuilt          int64
YearRemodAdd       int64
RoofStyle         object
RoofMatl          object
Exterior1st       object
Exterior2nd       object
MasVnrType        object
                  ...   
KitchenAbvGr       int64
KitchenQual       object
TotRmsAbvGrd       int64
Functional        object
Fireplaces         int64
GarageType        object
GarageYrBlt      float64
GarageFinish      object
GarageCars         int64
GarageArea         int64
GarageQual        object
GarageCond        object
PavedDrive        object
W

['Id', 'MSSubClass']

In [66]:
train_df.Street.value_counts()

Pave    1454
Grvl       6
Name: Street, dtype: int64

In [67]:
print(test_df['BsmtFinSF1'].dtype)  #发现train中的这个是int， test中是float
print(train_df['BsmtFinSF1'].dtype)   


test_df['BsmtFinSF1'].astype('int64')
print(train_df['BsmtFinSF1'].dtype) 

float64
int64
int64


In [68]:

##############这是直接把所有特征一起放进去变换的下面是每次放一个特征用循环，这个得到是array再转成DataFrame

scaler2 = preprocessing.StandardScaler()

scaler_para2 = scaler2.fit(train_df[number_columns[1:-1]])
array_number = scaler2.fit_transform(train_df[number_columns[1:-1]], scaler_para2)
pd.DataFrame(array_number, index=train_df.Id, columns=[ x + '_scaled' for x in number_columns[1:-1]])

########################################################################################################

MSSubClass_scaled  LotFrontage_scaled  LotArea_scaled  \
Id                                                            
1              0.073375       -2.293718e-01       -0.207142   
2             -0.872563        4.519361e-01       -0.091886   
3              0.073375       -9.311018e-02        0.073480   
4              0.309859       -4.564744e-01       -0.096897   
5              0.073375        6.336182e-01        0.375148   
6             -0.163109        6.790387e-01        0.360616   
7             -0.872563        2.248335e-01       -0.043379   
8              0.073375        6.454645e-16       -0.013513   
9             -0.163109       -8.652591e-01       -0.440659   
10             3.147673       -9.106796e-01       -0.310370   
11            -0.872563       -2.269135e-03        0.068469   
12             0.073375        6.790387e-01        0.141030   
13            -0.872563        6.454645e-16        0.245661   
14            -0.872563        9.515619e-01        0.013547   
15            -0.872563        6.454645e-16        0.040407   
16            -0.281352       -8.652591e-01       -0.440659   
17            -0.872563        6.454645e-16        0.072578   
18             0.782828        8.857191e-02        0.027478   
19            -0.872563       -1.839512e-01        0.318523   
20            -0.872563       -2.269135e-03       -0.296339   
21             0.073375        1.405767e+00        0.370638   
22            -0.281352       -5.927359e-01       -0.307464   
23            -0.872563        2.248335e-01       -0.077655   
24             1.492282       -1.183203e+00       -0.630680   
25            -0.872563        6.454645e-16       -0.227587   
...                 ...                 ...             ...   
1436          -0.872563        4.519361e-01       -0.212153   
1437          -0.872563       -4.564744e-01       -0.152020   
1438          -0.872563        1.178664e+00        0.193145   
1439          -0.872563        9.061413e-01       -0.311673   
1440           0.073375        4.519361e-01        0.106954   
1441           0.309859        4.065156e-01        0.101141   
1442           1.492282        6.454645e-16       -0.610435   
1443           0.073375        6.790387e-01        0.048725   
1444          -0.636078        6.454645e-16       -0.166652   
1445          -0.872563       -3.202128e-01       -0.202131   
1446           0.664586       -2.269135e-03       -0.212153   
1447          -0.872563        6.454645e-16        1.565986   
1448           0.073375        4.519361e-01       -0.051798   
1449          -0.163109       -2.269135e-03        0.125295   
1450           2.911188       -2.227875e+00       -0.900377   
1451           0.782828       -4.564744e-01       -0.152020   
1452          -0.872563        3.610951e-01       -0.125761   
1453           2.911188       -1.591987e+00       -0.685702   
1454          -0.872563        9.061413e-01        0.671505   
1455          -0.872563       -3.656333e-01       -0.302353   
1456           0.073375       -3.656333e-01       -0.260560   
1457          -0.872563        6.790387e-01        0.266407   
1458           0.309859       -1.839512e-01       -0.147810   
1459          -0.872563       -9.311018e-02       -0.080160   
1460          -0.872563        2.248335e-01       -0.058112   

      OverallQual_scaled  OverallCond_scaled  YearBuilt_scaled  \
Id                                                               
1               0.651479           -0.517200          1.050994   
2              -0.071836            2.179628          0.156734   
3               0.651479           -0.517200          0.984752   
4               0.651479           -0.517200         -1.863632   
5               1.374795           -0.517200          0.951632   
6              -0.795151           -0.517200          0.719786   
7               1.374795           -0.517200          1.084115   
8               0.651479            0.381743          0.057371   
9     

In [69]:
print(len(number_columns))
print(number_columns)

38
['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SalePrice']


In [70]:
scaler = preprocessing.StandardScaler()
# scaler_para_most = scaler.fit(train_df[number_columns[:-1]])
# print(scaler_para)

# print(train_df.columns)
# print(number_columns[:-1])
# print()
for column in number_columns[1:-1]:
    print(column)
    for i, df in enumerate(train_test):
        scaler_para = scaler.fit(df[column].as_matrix().reshape(-1, 1))
        if i == 0:
            train_df[column+'_scale'] = scaler.fit_transform(df[column].as_matrix().reshape(-1, 1), scaler_para)
        if i==1:
            test_df[column+'_scale'] = scaler.fit_transform(df[column].as_matrix().reshape(-1, 1), scaler_para)
train_df

MSSubClass
LotFrontage
LotArea
OverallQual
OverallCond
YearBuilt
YearRemodAdd
MasVnrArea
BsmtFinSF1
BsmtFinSF2
BsmtUnfSF
TotalBsmtSF
1stFlrSF
2ndFlrSF
LowQualFinSF
GrLivArea
BsmtFullBath
BsmtHalfBath
FullBath
HalfBath
BedroomAbvGr
KitchenAbvGr
TotRmsAbvGrd
Fireplaces
GarageYrBlt
GarageCars
GarageArea
WoodDeckSF
OpenPorchSF
EnclosedPorch
3SsnPorch
ScreenPorch
PoolArea
MiscVal
MoSold
YrSold


D:\annoconda\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


Id  MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  \
0        1          60       RL    65.000000     8450   Pave      Reg   
1        2          20       RL    80.000000     9600   Pave      Reg   
2        3          60       RL    68.000000    11250   Pave      IR1   
3        4          70       RL    60.000000     9550   Pave      IR1   
4        5          60       RL    84.000000    14260   Pave      IR1   
5        6          50       RL    85.000000    14115   Pave      IR1   
6        7          20       RL    75.000000    10084   Pave      Reg   
7        8          60       RL    70.049958    10382   Pave      IR1   
8        9          50       RM    51.000000     6120   Pave      Reg   
9       10         190       RL    50.000000     7420   Pave      Reg   
10      11          20       RL    70.000000    11200   Pave      Reg   
11      12          60       RL    85.000000    11924   Pave      IR1   
12      13          20       RL    70.049958    12968   Pave      IR2   
13      14          20       RL    91.000000    10652   Pave      IR1   
14      15          20       RL    70.049958    10920   Pave      IR1   
15      16          45       RM    51.000000     6120   Pave      Reg   
16      17          20       RL    70.049958    11241   Pave      IR1   
17      18          90       RL    72.000000    10791   Pave      Reg   
18      19          20       RL    66.000000    13695   Pave      Reg   
19      20          20       RL    70.000000     7560   Pave      Reg   
20      21          60       RL   101.000000    14215   Pave      IR1   
21      22          45       RM    57.000000     7449   Pave      Reg   
22      23          20       RL    75.000000     9742   Pave      Reg   
23      24         120       RM    44.000000     4224   Pave      Reg   
24      25          20       RL    70.049958     8246   Pave      IR1   
...    ...         ...      ...          ...      ...    ...      ...   
1435  1436          20       RL    80.000000     8400   Pave      Reg   
1436  1437          20       RL    60.000000     9000   Pave      Reg   
1437  1438          20       RL    96.000000    12444   Pave      Reg   
1438  1439          20       RM    90.000000     7407   Pave      Reg   
1439  1440          60       RL    80.000000    11584   Pave      Reg   
1440  1441          70       RL    79.000000    11526   Pave      IR1   
1441  1442         120       RM    70.049958     4426   Pave      Reg   
1442  1443          60       FV    85.000000    11003   Pave      Reg   
1443  1444          30       RL    70.049958     8854   Pave      Reg   
1444  1445          20       RL    63.000000     8500   Pave      Reg   
1445  1446          85       RL    70.000000     8400   Pave      Reg   
1446  1447          20       RL    70.049958    26142   Pave      IR1   
1447  1448          60       RL    80.000000    10000   Pave      Reg   
1448  1449          50       RL    70.000000    11767   Pave      Reg   
1449  1450         180       RM    21.000000     1533   Pave      Reg   
1450  1451          90       RL    60.000000     9000   Pave      Reg   
1451  1452          20       RL    78.000000     9262   Pave      Reg   
1452  1453         180       RM    35.000000     3675   Pave      Reg   
1453  1454          20       RL    90.000000    17217   Pave      Reg   
1454  1455          20       FV    62.000000     7500   Pave      Reg   
1455  1456          60       RL    62.000000     7917   Pave      Reg   
1456  1457          20       RL    85.000000    13175   Pave      Reg   
1457  1458          70       RL    66.000000     9042   Pave      Reg   
1458  1459          20       RL    68.000000     9717   Pave      Reg   
1459  1460          20       RL    75.000000     9937   Pave      Reg   

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0            Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1            Lvl    AllPub       FR2       Gtl      Veenker    

In [71]:
scaler.mean_

array([ 2007.76970528])

In [72]:
print(len(number_columns))
print(len(str_columns))

38
38


In [73]:
pd.get_dummies(train_df[['MSZoning','Street']])
#发现pd.get_dummies 如果放进去是Series的话，默认没有前缀，如果是DataFrame的话自己加上前缀

MSZoning_C (all)  MSZoning_FV  MSZoning_RH  MSZoning_RL  MSZoning_RM  \
0                    0            0            0            1            0   
1                    0            0            0            1            0   
2                    0            0            0            1            0   
3                    0            0            0            1            0   
4                    0            0            0            1            0   
5                    0            0            0            1            0   
6                    0            0            0            1            0   
7                    0            0            0            1            0   
8                    0            0            0            0            1   
9                    0            0            0            1            0   
10                   0            0            0            1            0   
11                   0            0            0            1            0   
12                   0            0            0            1            0   
13                   0            0            0            1            0   
14                   0            0            0            1            0   
15                   0            0            0            0            1   
16                   0            0            0            1            0   
17                   0            0            0            1            0   
18                   0            0            0            1            0   
19                   0            0            0            1            0   
20                   0            0            0            1            0   
21                   0            0            0            0            1   
22                   0            0            0            1            0   
23                   0            0            0            0            1   
24                   0            0            0            1            0   
...                ...          ...          ...          ...          ...   
1435                 0            0            0            1            0   
1436                 0            0            0            1            0   
1437                 0            0            0            1            0   
1438                 0            0            0            0            1   
1439                 0            0            0            1            0   
1440                 0            0            0            1            0   
1441                 0            0            0            0            1   
1442                 0            1            0            0            0   
1443                 0            0            0            1            0   
1444                 0            0            0            1            0   
1445                 0            0            0            1            0   
1446                 0            0            0            1            0   
1447                 0            0            0            1            0   
1448                 0            0            0            1            0   
1449                 0            0            0            0            1   
1450                 0            0            0            1            0   
1451                 0            0            0            1            0   
1452                 0            0            0            0            1   
1453                 0            0            0            1            0   
1454                 0            1            0            0            0   
1455                 0            0            0            1            0   
1456                 0            0            0            1            0   
1457                 0            0            0            1            0   
1458                 0            0            0            1            0   
1459                 0      

In [74]:
pd.set_option('display.max_columns', 100)

In [75]:
for i, df in enumerate(train_test):
    if i == 0:
        train_str_dummies_columns = pd.get_dummies(df[str_columns])
    if i ==1:
        test_str_dummies_columns = pd.get_dummies(df[str_columns])
print(len(test_str_dummies_columns.columns))
print(len(train_str_dummies_columns.columns))
print(test_str_dummies_columns.columns)
print(train_str_dummies_columns.columns)

train_min_test = list(set(train_str_dummies_columns.columns.tolist()) - set(test_str_dummies_columns.columns.tolist()))
# train_str_dummies_columns.to_csv('train_str.csv')
# test_str_dummies_columns.to_csv('tesr_str.csv')

218
234
Index(['MSZoning_C (all)', 'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL',
       'MSZoning_RM', 'Street_Grvl', 'Street_Pave', 'LotShape_IR1',
       'LotShape_IR2', 'LotShape_IR3',
       ...
       'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='object', length=218)
Index(['MSZoning_C (all)', 'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL',
       'MSZoning_RM', 'Street_Grvl', 'Street_Pave', 'LotShape_IR1',
       'LotShape_IR2', 'LotShape_IR3',
       ...
       'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='object', length=234)


In [76]:
for column in train_min_test: #看一下不一样的原因  train内容更丰富
    aa = column.split('_')[0]
    for df in train_test:
        print(df[aa].value_counts())
    print('\n')

CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Roll          1
Membran       1
Metal         1
ClyTile       1
Name: RoofMatl, dtype: int64
CompShg    1442
Tar&Grv      12
WdShake       4
WdShngl       1
Name: RoofMatl, dtype: int64


AllPub    1459
NoSeWa       1
Name: Utilities, dtype: int64
AllPub    1459
Name: Utilities, dtype: int64


CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Roll          1
Membran       1
Metal         1
ClyTile       1
Name: RoofMatl, dtype: int64
CompShg    1442
Tar&Grv      12
WdShake       4
WdShngl       1
Name: RoofMatl, dtype: int64


TA    1392
Fa      48
Gd      14
Po       3
Ex       3
Name: GarageQual, dtype: int64
TA    1371
Fa      76
Gd      10
Po       2
Name: GarageQual, dtype: int64


Norm      1445
Feedr        6
Artery       2
PosN         2
RRNn         2
PosA         1
RRAe         1
RRAn         1
Name: Condition2, dtype: int64
Norm      1444
Feedr        7
PosA         3
Artery       3
PosN         2


In [77]:
train_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       ...
       'GarageArea_scale', 'WoodDeckSF_scale', 'OpenPorchSF_scale',
       'EnclosedPorch_scale', '3SsnPorch_scale', 'ScreenPorch_scale',
       'PoolArea_scale', 'MiscVal_scale', 'MoSold_scale', 'YrSold_scale'],
      dtype='object', length=112)

In [78]:
print(len(train_df.filter(regex='_scale').columns)) #number_columns一共38个，除去ID和saleprice正好是36个，
train_df.filter(regex='_scale').columns

36


Index(['MSSubClass_scale', 'LotFrontage_scale', 'LotArea_scale',
       'OverallQual_scale', 'OverallCond_scale', 'YearBuilt_scale',
       'YearRemodAdd_scale', 'MasVnrArea_scale', 'BsmtFinSF1_scale',
       'BsmtFinSF2_scale', 'BsmtUnfSF_scale', 'TotalBsmtSF_scale',
       '1stFlrSF_scale', '2ndFlrSF_scale', 'LowQualFinSF_scale',
       'GrLivArea_scale', 'BsmtFullBath_scale', 'BsmtHalfBath_scale',
       'FullBath_scale', 'HalfBath_scale', 'BedroomAbvGr_scale',
       'KitchenAbvGr_scale', 'TotRmsAbvGrd_scale', 'Fireplaces_scale',
       'GarageYrBlt_scale', 'GarageCars_scale', 'GarageArea_scale',
       'WoodDeckSF_scale', 'OpenPorchSF_scale', 'EnclosedPorch_scale',
       '3SsnPorch_scale', 'ScreenPorch_scale', 'PoolArea_scale',
       'MiscVal_scale', 'MoSold_scale', 'YrSold_scale'],
      dtype='object')

In [79]:
len(train_str_dummies_columns[test_str_dummies_columns.columns.tolist()].columns)

218

In [80]:
final_train_df = pd.concat([train_df.filter(regex='_scale'), train_str_dummies_columns[test_str_dummies_columns.columns.tolist()]], axis=1)
print(len(final_train_df.columns))
final_train_df.to_csv('./data/final_train_feature.csv')
final_train_df

254


MSSubClass_scale  LotFrontage_scale  LotArea_scale  OverallQual_scale  \
0             0.073375      -2.293718e-01      -0.207142           0.651479   
1            -0.872563       4.519361e-01      -0.091886          -0.071836   
2             0.073375      -9.311018e-02       0.073480           0.651479   
3             0.309859      -4.564744e-01      -0.096897           0.651479   
4             0.073375       6.336182e-01       0.375148           1.374795   
5            -0.163109       6.790387e-01       0.360616          -0.795151   
6            -0.872563       2.248335e-01      -0.043379           1.374795   
7             0.073375       6.454645e-16      -0.013513           0.651479   
8            -0.163109      -8.652591e-01      -0.440659           0.651479   
9             3.147673      -9.106796e-01      -0.310370          -0.795151   
10           -0.872563      -2.269135e-03       0.068469          -0.795151   
11            0.073375       6.790387e-01       0.141030           2.098110   
12           -0.872563       6.454645e-16       0.245661          -0.795151   
13           -0.872563       9.515619e-01       0.013547           0.651479   
14           -0.872563       6.454645e-16       0.040407          -0.071836   
15           -0.281352      -8.652591e-01      -0.440659           0.651479   
16           -0.872563       6.454645e-16       0.072578          -0.071836   
17            0.782828       8.857191e-02       0.027478          -1.518467   
18           -0.872563      -1.839512e-01       0.318523          -0.795151   
19           -0.872563      -2.269135e-03      -0.296339          -0.795151   
20            0.073375       1.405767e+00       0.370638           1.374795   
21           -0.281352      -5.927359e-01      -0.307464           0.651479   
22           -0.872563       2.248335e-01      -0.077655           1.374795   
23            1.492282      -1.183203e+00      -0.630680          -0.795151   
24           -0.872563       6.454645e-16      -0.227587          -0.795151   
...                ...                ...            ...                ...   
1435         -0.872563       4.519361e-01      -0.212153          -0.071836   
1436         -0.872563      -4.564744e-01      -0.152020          -1.518467   
1437         -0.872563       1.178664e+00       0.193145           1.374795   
1438         -0.872563       9.061413e-01      -0.311673          -0.071836   
1439          0.073375       4.519361e-01       0.106954           0.651479   
1440          0.309859       4.065156e-01       0.101141          -0.071836   
1441          1.492282       6.454645e-16      -0.610435          -0.071836   
1442          0.073375       6.790387e-01       0.048725           2.821425   
1443         -0.636078       6.454645e-16      -0.166652          -0.071836   
1444         -0.872563      -3.202128e-01      -0.202131           0.651479   
1445          0.664586      -2.269135e-03      -0.212153          -0.071836   
1446         -0.872563       6.454645e-16       1.565986          -0.795151   
1447          0.073375       4.519361e-01      -0.051798           1.374795   
1448         -0.163109      -2.269135e-03       0.125295          -1.518467   
1449          2.911188      -2.227875e+00      -0.900377          -0.795151   
1450          0.782828      -4.564744e-01      -0.152020          -0.795151   
1451         -0.872563       3.610951e-01      -0.125761           1.374795   
1452          2.911188      -1.591987e+00      -0.685702          -0.795151   
1453         -0.872563       9.061413e-01       0.671505          -0.795151   
1454         -0.872563      -3.656333e-01      -0.302353           0.651479   
1455          0.073375      -3.656333e-01      -0.260560          -0.071836   
1456         -0.872563       6.790387e-01       0.266407          -0.071836   
1457          0.309859      -1.839512e-01      -0.147810           0.651479   
1458         -0.872563      -9.311018e-02      -0.080160

In [81]:
final_test_df = pd.concat([test_df.filter(regex='_scale'), test_str_dummies_columns], axis=1)
print(len(final_test_df.columns))
# final_test_df.to_csv('./data/final_test_feature.csv')
final_test_df

254


MSSubClass_scale  LotFrontage_scale  LotArea_scale  OverallQual_scale  \
0            -0.874711           0.555587       0.363929          -0.751101   
1            -0.874711           0.604239       0.897861          -0.054877   
2             0.061351           0.263676       0.809646          -0.751101   
3             0.061351           0.458284       0.032064          -0.054877   
4             1.465443          -1.244533      -0.971808           1.337571   
5             0.061351           0.312328       0.036505          -0.054877   
6            -0.874711           0.000000      -0.371261          -0.054877   
7             0.061351          -0.271495      -0.286074          -0.054877   
8            -0.874711           0.798847       0.072033           0.641347   
9            -0.874711           0.069068      -0.286478          -1.447325   
10            1.465443          -2.071615      -0.799618           0.641347   
11            2.401505          -2.314875      -1.643007          -0.054877   
12            2.401505          -2.314875      -1.643007          -0.751101   
13            2.401505          -2.168919      -1.521889          -0.054877   
14            1.465443          -2.168919      -1.521889           0.641347   
15            0.061351           1.625929       0.613434           2.033795   
16           -0.874711           1.236714       0.618480           1.337571   
17           -0.874711           1.042106       0.343339           2.033795   
18           -0.874711           0.506935       0.868590           1.337571   
19           -0.874711           2.015144       0.904522           2.033795   
20            0.061351           1.771885       0.773310           1.337571   
21            1.465443          -1.341837      -0.542442           1.337571   
22           -0.874711           1.528625       1.751142          -0.054877   
23            1.465443          -1.244533      -1.335568           0.641347   
24            0.529382          -0.076887       0.702658           0.641347   
...                ...                ...            ...                ...   
1434          1.465443          -1.341837      -0.821823           1.337571   
1435          1.465443          -1.195881      -1.206576           1.337571   
1436         -0.874711           0.020416       2.777824          -0.054877   
1437          0.763397          -0.174191      -0.289506          -0.054877   
1438         -0.874711           0.069068      -0.141943           1.337571   
1439          0.529382           3.474702       0.254519          -0.054877   
1440         -0.874711           0.000000       8.131674          -0.054877   
1441         -0.874711           0.000000      -0.347441          -0.054877   
1442         -0.874711           1.285366       0.766851           1.337571   
1443         -0.874711           0.944803       0.354845           2.033795   
1444         -0.874711           2.744923       4.326125          -3.535998   
1445          0.763397           0.458284      -0.565051           0.641347   
1446          2.401505          -1.341837      -1.444171          -0.751101   
1447         -0.874711          -0.514755       0.071226          -0.751101   
1448          0.763397           0.000000       0.407128          -0.751101   
1449          2.869536          -2.314875      -1.685399          -1.447325   
1450          2.401505          -2.314875      -1.682573          -1.447325   
1451         -0.874711           0.555587       0.719614          -0.751101   
1452          2.401505          -2.314875      -1.672682          -1.447325   
1453          2.401505          -2.314875      -1.674095          -1.447325   
1454          2.401505          -2.314875      -1.591330          -1.447325   
1455          2.401505          -2.314875      -1.599808          -1.447325   
1456         -0.874711           4.447740       2.055150          -0.751101   
1457          0.646389          -0.320147       0.125527

In [82]:
train_df['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
5       143000
6       307000
7       200000
8       129900
9       118000
10      129500
11      345000
12      144000
13      279500
14      157000
15      132000
16      149000
17       90000
18      159000
19      139000
20      325300
21      139400
22      230000
23      129900
24      154000
         ...  
1435    174000
1436    120500
1437    394617
1438    149700
1439    197000
1440    191000
1441    149300
1442    310000
1443    121000
1444    179600
1445    129000
1446    157900
1447    240000
1448    112000
1449     92000
1450    136000
1451    287090
1452    145000
1453     84500
1454    185000
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [83]:
scaler_y = preprocessing.StandardScaler()
scaler_y.fit(train_df['SalePrice'].as_matrix().reshape(-1, 1))
y_scaled = scaler_y.fit_transform(train_df['SalePrice'].as_matrix().reshape(-1, 1), scaler_y)
y_scaled

D:\annoconda\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ..., 
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [84]:
print(scaler_y.var_)
scaler_y.mean_


[  6.30678859e+09]


array([ 180921.19589041])

In [85]:
y_scaled * np.sqrt(scaler_y.var_) + scaler_y.mean_  #这个是后面准备用到的恢复y的公式

array([[ 208500.],
       [ 181500.],
       [ 223500.],
       ..., 
       [ 266500.],
       [ 142125.],
       [ 147500.]])

In [86]:
final_train_df['price'] = y_scaled
print(len(final_train_df.columns))
print(len(final_test_df.columns))

255
254


In [109]:
print(final_train_df.info())
print(final_test_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 255 entries, MSSubClass_scale to price
dtypes: float64(37), uint8(218)
memory usage: 732.9 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 254 entries, MSSubClass_scale to SaleCondition_Partial
dtypes: float64(36), uint8(218)
memory usage: 721.0 KB
None


In [87]:
#################################至此 数据预处理完成##############################  y_scaled没有存进csv中###############
#########################################################################################################################

In [107]:
print(final_test_df.as_matrix())
final_train_df.as_matrix()[:, :-1]

[[-0.87471081  0.55558736  0.36392912 ...,  0.          1.          0.        ]
 [-0.87471081  0.60423927  0.89786065 ...,  0.          1.          0.        ]
 [ 0.06135085  0.26367594  0.80964587 ...,  0.          1.          0.        ]
 ..., 
 [-0.87471081  4.44773966  2.05514965 ...,  0.          0.          0.        ]
 [ 0.64638939 -0.3201469   0.12552719 ...,  0.          1.          0.        ]
 [ 0.06135085  0.26367594 -0.03879049 ...,  0.          1.          0.        ]]


array([[ 0.07337496, -0.22937175, -0.20714171, ...,  0.        ,
         1.        ,  0.        ],
       [-0.87256276,  0.4519361 , -0.09188637, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.07337496, -0.09311018,  0.07347998, ...,  0.        ,
         1.        ,  0.        ],
       ..., 
       [ 0.30985939, -0.18395123, -0.14781027, ...,  0.        ,
         1.        ,  0.        ],
       [-0.87256276, -0.09311018, -0.08016039, ...,  0.        ,
         1.        ,  0.        ],
       [-0.87256276,  0.22483348, -0.05811155, ...,  0.        ,
         1.        ,  0.        ]])

In [88]:
#划分数据集###

In [89]:
train_split, test_split = cross_validation.train_test_split(final_train_df, test_size = 0.3)

In [90]:
print(len(test_split.index))
len(train_split.index)


438


1022

In [110]:
#####建立模型#############
# linear_model.
linear_reg_model = linear_model.LinearRegression()
# linear_reg_model.fit(train_split.as_matrix()[:, :-1], y=train_split.as_matrix()[:, -1])
linear_reg_model.fit(final_train_df.as_matrix()[:, :-1], y=final_train_df.as_matrix()[:, -1])
linear_reg_model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [114]:
# predict_y = linear_reg_model.predict(final_test_df.as_matrix())
predict_y = linear_reg_model.predict(test_split.as_matrix()[:, :-1])
print(len(predict_y))
print(linear_reg_model.coef_)
predict_y

438
[ -5.99622877e-02  -1.78805032e-02   6.14947420e-02   1.37555839e-01
   6.49682581e-02   5.73402461e-02   2.38515014e-02   4.91925318e-02
   2.17034253e+10   7.67637675e+09   2.10262367e+10  -2.08757906e+10
  -3.99495675e+10  -4.51103863e+10  -5.02465775e+09   5.43025864e+10
   2.89449692e-02   5.60951233e-03   4.67903614e-02   5.17034531e-03
  -3.20377350e-02  -3.38163376e-02   4.30397391e-02   2.95019150e-02
  -6.04915619e-03   8.95171762e-02  -7.92789459e-03   2.06289291e-02
   2.28428841e-03   7.29835033e-03   1.79262161e-02   2.26068497e-02
   1.55959129e-02  -5.67233562e-03  -1.31174680e-02  -1.20159984e-02
  -1.62662424e+10  -1.62662424e+10  -1.62662424e+10  -1.62662424e+10
  -1.62662424e+10   1.32119516e+10   1.32119516e+10  -2.34826807e+10
  -2.34826807e+10  -2.34826807e+10  -2.34826807e+10   2.57446301e+09
   2.57446301e+09   2.57446301e+09   2.57446301e+09   7.28614062e-01
   7.13997911e+09   7.13997911e+09   7.13997911e+09   7.13997911e+09
   7.13997911e+09  -5.22333002

array([  9.89870071e-01,  -7.12970734e-01,   1.29613876e-01,
         2.03678894e+00,   7.64827728e-02,  -1.38254166e-01,
         1.07303810e+00,  -1.70355225e+00,  -2.09123611e-01,
         7.38706589e-01,   2.58405685e-01,  -4.04981613e-01,
        -2.19377518e-01,  -9.16128159e-01,  -1.37451363e+00,
         7.29530334e-01,   4.83232498e-01,  -8.75517845e-01,
         3.32956314e-01,  -1.65056229e-01,   3.15958023e-01,
         3.60303879e-01,  -1.01501465e+00,  -9.19805527e-01,
        -1.04917526e-01,   1.58742905e-01,   5.26109695e-01,
        -4.47154999e-01,   1.43319511e+00,  -5.58318138e-01,
         3.12482834e-01,   2.15330124e-01,  -3.65638733e-03,
         1.38899422e+00,  -5.10501862e-02,   3.59783173e-02,
        -1.97227478e-01,  -1.10082626e-01,   6.64686203e-01,
        -1.17156792e+00,   2.11884499e-01,  -3.88811111e-01,
         6.69429779e-01,  -3.40223312e-01,  -6.85380936e-01,
         1.51132393e+00,  -8.46075058e-01,  -7.40804672e-01,
         1.88169479e-01,

In [ ]:
print(len(test_split.iloc[:, -1]))
test_split.iloc[:, -1]

In [98]:
print(final_test_df.info())
print('--'*20)
print(final_train_df.info())
print('--'*20)
print(train_split.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Columns: 254 entries, MSSubClass_scale to SaleCondition_Partial
dtypes: float64(36), uint8(218)
memory usage: 721.0 KB
None
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 255 entries, MSSubClass_scale to price
dtypes: float64(37), uint8(218)
memory usage: 732.9 KB
None
----------------------------------------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1022 entries, 872 to 62
Columns: 255 entries, MSSubClass_scale to price
dtypes: float64(37), uint8(218)
memory usage: 521.0 KB
None


In [95]:
# linear_reg_model = linear_model.LinearRegression()
# linear_reg_model.fit(train_split.as_matrix()[:, :-1], y=train_split.as_matrix()[:, -1])
# predict_y = linear_reg_model.predict(test_split.as_matrix()[:, :-1])



linear_regression = linear_model.LinearRegression()
#linear_reg_model.fit(train_split.as_matrix()[:, :-1], y=train_split.as_matrix()[:, -1])
# linear_reg_model1.fit(X = final_train_df.as_matrix()[:438, :-1], y =final_train_df.as_matrix()[:438, -1])
linear_regression.fit(X = train_split.as_matrix()[:, :-1], y=train_split.as_matrix()[:, -1])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [120]:
import xgboost as xgb
model_xgb = xgb.XGBRegressor(n_estimators=360, max_depth=6, learning_rate=0.1)
model_xgb.fit(final_train_df.as_matrix()[:, :-1], final_train_df.as_matrix()[:, -1])
model_xgb

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=6, min_child_weight=1, missing=None, n_estimators=360,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [123]:
xgb_pre_y = model_xgb.predict(final_test_df.as_matrix())

In [96]:
pre_y = linear_regression.predict(final_test_df.as_matrix())
pre_y

array([  3.75815887e+10,  -3.63489144e+09,   7.78308943e+09, ...,
         6.34979664e+09,   3.18247347e+10,  -1.08683963e+10])

In [124]:
pre_y_rescaled = xgb_pre_y * np.sqrt(scaler_y.var_) + scaler_y.mean_
pre_y_rescaled

array([ 129930.92985729,  153950.33586326,  188817.74669613, ...,
        164572.45473647,  116828.1008195 ,  213170.56530208])

In [127]:
submission = pd.DataFrame(columns=['Id', 'SalePrice'])

In [128]:
submission['Id'] = raw_test_df['Id']

In [129]:
submission['SalePrice'] = pre_y_rescaled

In [132]:
submission.to_csv('./data/submission.csv', index=False)

In [8]:
np.logspace(1, 2.7, 10)

array([  10.        ,   15.44859148,   23.86589787,   36.86945065,
         56.95810811,   87.99225436,  135.93563909,  210.00141557,
        324.42260792,  501.18723363])